name: todo_frontend
description: Simple Flutter ToDo client for ToDoListToPeyman
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
